<a href="https://colab.research.google.com/github/parthkohli92/Tensorflow/blob/main/tensorflow_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow fundamentals

we're going to try:
* Tensors
* Getting information from tensors
* Manipulate Tensors
* Tensors and Numpy
* Using @tf.function (a way to speed up regular python functions)
* Using GPUs with Tensorflow (or TPUs)



## Tensors

In [29]:
import tensorflow as tf 
print(tf.__version__)

2.6.0


In [30]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [31]:
scalar.ndim # Number of dimensions of a tensor

0

In [32]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [33]:
vector.ndim

1

In [34]:
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [35]:
matrix.ndim

2

In [36]:
matrix2 = tf.constant([[10.,6.],
                       [3.,9.],
                       [5.,10.]], dtype=tf.float16)
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  6.],
       [ 3.,  9.],
       [ 5., 10.]], dtype=float16)>

In [37]:
matrix2.ndim

2

In [38]:
matrix3 = tf.constant([[[2,3,4],
                       [5,6,7],
                        [2,3,4]],
                      [[2,3,4],
                       [5,6,7],
                       [2,3,4]],
                      [[2,3,4],
                       [5,6,7],
                       [2,3,4]]])
matrix3

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[2, 3, 4],
        [5, 6, 7],
        [2, 3, 4]],

       [[2, 3, 4],
        [5, 6, 7],
        [2, 3, 4]],

       [[2, 3, 4],
        [5, 6, 7],
        [2, 3, 4]]], dtype=int32)>

In [39]:
matrix3.ndim

3

In [40]:
# Tensors with Variables 
changeable = tf.Variable([10,2,4])
unchangeable = tf.constant([10,2,4])

changeable, unchangeable

(<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([10,  2,  4], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([10,  2,  4], dtype=int32)>)

Now we'll try to change one of the elements of the changable tensors

In [41]:
changeable[2].assign(7)
changeable

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([10,  2,  7], dtype=int32)>

## Creating Random Tensors

In [42]:
random1 = tf.random.Generator.from_seed(42)
random1 = random1.normal(shape=(6,3))
random2 = tf.random.Generator.from_seed(42)
random2 = random2.normal(shape=(6,3))


In [43]:
random1, random2, random1 == random2

(<tf.Tensor: shape=(6, 3), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535805 ],
        [-0.57166284,  0.1480774 , -0.23362993],
        [-0.3522796 ,  0.40621263, -1.0523509 ],
        [ 1.2054597 ,  1.6874489 , -0.4462975 ]], dtype=float32)>,
 <tf.Tensor: shape=(6, 3), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535805 ],
        [-0.57166284,  0.1480774 , -0.23362993],
        [-0.3522796 ,  0.40621263, -1.0523509 ],
        [ 1.2054597 ,  1.6874489 , -0.4462975 ]], dtype=float32)>,
 <tf.Tensor: shape=(6, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>)

In [44]:
# other ways to make tensors
tf.ones(shape=(6,3))

<tf.Tensor: shape=(6, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [45]:
tf.zeros(shape=(4,8))

<tf.Tensor: shape=(4, 8), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [46]:
# Turning numbers into tensors

import numpy as np 

numpyA = np.arange(1,25, dtype=np.int32)
A = tf.constant(numpyA,
                shape=[2,4,3])

numpyA, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

In [47]:
# Getting information from tensors.

rank4 = tf.zeros([2,3,4,5])
rank4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [48]:
rank2 = tf.constant([[10,7],
                    [3,4]])

In [49]:
rank2.shape

TensorShape([2, 2])

# Manipulating tensors 

In [50]:
# Basic operations 
tensor = tf.constant([[10,10],[5,5]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 20],
       [15, 15]], dtype=int32)>

In [51]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 100],
       [ 25,  25]], dtype=int32)>

In [52]:
tf.multiply(tensor,10) / 5

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[20., 20.],
       [10., 10.]])>

In [53]:
# Matrix multiplications
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10 10]
 [ 5  5]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[150, 150],
       [ 75,  75]], dtype=int32)>

In [54]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[150, 150],
       [ 75,  75]], dtype=int32)>

mismatched shaped tensors

In [55]:
X1 = tf.constant([[1,2],
                 [3,4],
                 [5,6]])

X2 = tf.constant([[7,8],
                 [9,10],
                 [11,12]])

X1, X2

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [56]:
X1 @ X2

InvalidArgumentError: ignored

so we will reshape x and y 

In [57]:
Yal= tf.reshape(X2, shape=(2,3))

In [58]:
X1 @ Yal

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [59]:
tf.transpose(X1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [60]:
tf.matmul(tf.transpose(X1), X2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

## The dot product 

In [61]:
tf.tensordot(tf.transpose(X1), X2, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [62]:
tf.matmul(X1, tf.transpose(X2))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

## Changing the datatype of a tensor 

In [63]:
B = tf.constant([1.7, 7.4])

C = tf.constant([1,7])

B,C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>)

In [64]:
# Squeezing a tensor

G = tf.constant(np.random.randint(0,100,50), shape=(1,1,1,1,50))

G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [65]:
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim

(TensorShape([50]), 1)

# One hot encoding 

In [66]:
some_list = [0,1,2,3]


tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [67]:
tf.one_hot(some_list, depth=4, on_value="we're alive", off_value="Offline")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b"we're alive", b'Offline', b'Offline', b'Offline'],
       [b'Offline', b"we're alive", b'Offline', b'Offline'],
       [b'Offline', b'Offline', b"we're alive", b'Offline'],
       [b'Offline', b'Offline', b'Offline', b"we're alive"]], dtype=object)>

## Using @tf.function

In [68]:
def function(x,y):
  return x+ y + 2

x = tf.constant(np.arange(0,20))
y = tf.constant(np.arange(20,40))

function(x,y)

<tf.Tensor: shape=(20,), dtype=int64, numpy=
array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54,
       56, 58, 60])>

In [69]:
@tf.function
def tf_function(x, y):
  return x + y +4 

tf_function(x,y)  

<tf.Tensor: shape=(20,), dtype=int64, numpy=
array([24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56,
       58, 60, 62])>

### Some Examples

In [77]:
A0= tf.constant([10,10])
A01= tf.constant(10)
A02=tf.constant([[1,2],
             [2,3]])
A03= tf.constant([[[1,2],
             [2,3]],
            [[1,2],
             [2,3]],
            [[1,2],
             [2,3]]])
A0.ndim, A01.ndim, A02.ndim, A03.ndim

(1, 0, 2, 3)

In [79]:
random11 = tf.random.Generator.from_seed(42)
random11 = random11.normal(shape=(5,300))
random22 = tf.random.Generator.from_seed(42)
random22 = random22.normal(shape=(5,300))

In [82]:
A04= (random11, random22)
A04

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, ..., -1.071834  ,
         -1.0722276 , -0.00586287],
        [-0.88051033, -0.32426047, -2.4847078 , ...,  0.16512105,
          1.155565  , -0.10707551],
        [-1.5306779 , -0.86202925, -0.16359143, ...,  0.34288085,
          1.216793  , -1.24293   ],
        [ 0.84324265, -0.23379943,  0.4276398 , ..., -1.0428714 ,
         -0.73970354,  0.0177109 ],
        [ 0.04888754, -0.66408694, -1.787366  , ...,  0.1947453 ,
          0.5656089 ,  0.18439196]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, ..., -1.071834  ,
         -1.0722276 , -0.00586287],
        [-0.88051033, -0.32426047, -2.4847078 , ...,  0.16512105,
          1.155565  , -0.10707551],
        [-1.5306779 , -0.86202925, -0.16359143, ...,  0.34288085,
          1.216793  , -1.24293   ],
        [ 0.84324265, -0.23379943,  0.4276398 , ..., -1.0428714 

In [86]:
random22.ndim

2

In [88]:
random11 @ random22

InvalidArgumentError: ignored